name: wnet-diff
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - nltk>=3.6.0
  - pandas>=1.3.0
  - networkx>=2.6.0
  - matplotlib>=3.4.0
  - pygraphviz>=1.7
  - pydot>=1.4.2
  - pip
